"""Tests for the implementation ledger and its effect on ideation.

Integration tests against the live database, because the thing worth proving is
that the ledger and the need assessment agree with each other — which a mock
would assume rather than demonstrate.

Every test cleans up after itself: this table is the one place in the project
holding data that cannot be regenerated by re-running the pipeline, so a test
that leaves rows behind would corrupt a real ledger.
"""

from __future__ import annotations

import pytest

from src.decision import implementations as impl
from src.decision.parameters import _derive, load_features

HIGH_SLIDE = "G07017"      # Malayattoor-Neeleswaram
INLAND = "G07049"          # Thiruvaniyoor

pytestmark = pytest.mark.skipif(
    not impl.STATUSES, reason="implementation module unavailable")


@pytest.fixture(scope="module")
def frame():
    return _derive(load_features())


@pytest.fixture
def logged():
    """One ledger row, removed again however the test ends."""
    created = impl.create(
        {"title": "pytest fixture — slope works", "domain": "environment",
         "addresses": "hazard_exposure", "est_cost_inr_crore": 7.5,
         "feasibility": "high", "conditions": ["Geotechnical assessment"],
         "what": "test row"},
        [HIGH_SLIDE], origin="test")
    yield created
    _delete(created["id"])


def _delete(implementation_id: int) -> None:
    import psycopg2

    from src.storage.postgres.load import connection_string
    with psycopg2.connect(connection_string()) as conn, conn.cursor() as cur:
        cur.execute("DELETE FROM implementation WHERE id = %s", (implementation_id,))
        conn.commit()


def test_a_new_implementation_starts_planned_and_logs_an_event(logged):
    assert logged["status"] == "planned"
    assert logged["est_cost_inr_crore"] == 7.5
    story = impl.history(logged["id"])
    assert [e["to_status"] for e in story["events"]] == ["planned"]
    assert story["events"][0]["from_status"] is None


def test_the_status_lifecycle_runs_forward(logged):
    assert impl.set_status(logged["id"], "in_progress")["status"] == "in_progress"
    done = impl.set_status(logged["id"], "completed", note="signed off")
    assert done["status"] == "completed"
    assert done["completed_at"] is not None
    assert [e["to_status"] for e in impl.history(logged["id"])["events"]] == \
        ["planned", "in_progress", "completed"]


def test_an_illegal_transition_is_refused(logged):
    """A tracker that lets `completed` become `planned` cannot answer
    "what is in progress", which is the question it exists to answer."""
    impl.set_status(logged["id"], "in_progress")
    impl.set_status(logged["id"], "completed")
    with pytest.raises(ValueError, match="cannot move"):
        impl.set_status(logged["id"], "planned")
    with pytest.raises(ValueError, match="cannot move"):
        impl.set_status(logged["id"], "in_progress")
    assert impl.history(logged["id"])["allowed_next"] == []


def test_setting_the_same_status_is_a_no_op(logged):
    again = impl.set_status(logged["id"], "planned")
    assert again["status"] == "planned"
    assert len(impl.history(logged["id"])["events"]) == 1


def test_an_unknown_id_raises_rather_than_inventing_a_row():
    with pytest.raises(KeyError):
        impl.set_status(10**9, "in_progress")
    with pytest.raises(KeyError):
        impl.history(10**9)


def test_creation_requires_a_title_and_an_area():
    with pytest.raises(ValueError):
        impl.create({"title": "   "}, [HIGH_SLIDE])
    with pytest.raises(ValueError):
        impl.create({"title": "no area"}, [])


def test_coverage_is_keyed_on_parameter_and_area(logged):
    """The join that stops the system re-proposing committed work."""
    covered = impl.coverage([HIGH_SLIDE])["by_parameter_and_area"]
    assert f"hazard_exposure|{HIGH_SLIDE}" in covered
    # Not claimed for an area the work does not touch.
    assert f"hazard_exposure|{INLAND}" not in impl.coverage([INLAND])["by_parameter_and_area"]


def test_cancelled_work_releases_the_need_again(logged):
    """A cancelled project leaves the gap wide open; the system must raise it.

    Asserted on this item's own id rather than on the key, because other rows
    may legitimately cover the same parameter in the same area — the invariant
    is that *this* cancelled item stops counting, not that the key empties.
    """
    key = f"hazard_exposure|{HIGH_SLIDE}"

    def ids_for(k):
        return {e["id"] for e in
                impl.coverage([HIGH_SLIDE])["by_parameter_and_area"].get(k, [])}

    assert logged["id"] in ids_for(key)
    impl.set_status(logged["id"], "cancelled", note="funding withdrawn")
    assert logged["id"] not in ids_for(key)
    assert "cancelled" not in impl.ACTIVE_STATUSES


def test_committed_spend_excludes_cancelled_work(logged):
    before = impl.listing(admin_ids=[HIGH_SLIDE])["committed_inr_crore"]
    impl.set_status(logged["id"], "cancelled")
    after = impl.listing(admin_ids=[HIGH_SLIDE])["committed_inr_crore"]
    assert after == pytest.approx(before - 7.5)


# --- the effect on need assessment and ideation -----------------------------

def test_a_covered_need_keeps_its_measured_severity(logged, frame):
    """The central discipline: an intention never edits a measurement.

    Marking drainage work complete must not move `flood_risk`, because the
    figure is KSDMA's. Only a re-measurement may change a measurement.
    """
    from src.decision.needs import assess

    bare = assess([HIGH_SLIDE], frame, with_coverage=False)
    annotated = assess([HIGH_SLIDE], frame, with_coverage=True)
    bare_sev = {n["parameter"]: n["severity"] for n in bare["ranked"]}
    ann_sev = {n["parameter"]: n["severity"] for n in annotated["ranked"]}
    assert bare_sev == ann_sev, "coverage must not alter severity"

    hazard = next(n for n in annotated["ranked"] if n["parameter"] == "hazard_exposure")
    assert hazard["addressed_by"], "expected the logged work to be attached"
    assert hazard["addressed_by"][0]["status"] == "planned"
    assert annotated["covered_count"] >= 1


def test_the_brief_tells_the_agent_not_to_repropose_covered_work(logged, frame):
    from src.decision.ideate import _domain_brief, _hazard_blocks
    from src.decision.needs import assess

    needs = assess([HIGH_SLIDE], frame)
    brief = _domain_brief("environment", needs["by_domain"]["environment"], 30.0,
                          [{"admin_name": "Malayattoor", "population": None}],
                          _hazard_blocks([HIGH_SLIDE], frame),
                          impl.covered_titles([HIGH_SLIDE]))
    assert "ALREADY BEING ADDRESSED" in brief
    assert "WORK ALREADY LOGGED IN YOUR DOMAIN" in brief
    assert "pytest fixture — slope works" in brief
    assert "Do NOT propose this again" in brief


def test_a_repeated_proposal_is_flagged_even_if_the_agent_ignores_the_brief(logged):
    """An instruction is not a guarantee, least of all on a small local model."""
    from src.decision.ideate import _flag_duplicates

    existing = impl.covered_titles([HIGH_SLIDE])
    proposals = {"environment": {"available": True, "ideas": [
        {"title": "PyTest Fixture - Slope Works", "addresses": "slope"},       # title match
        {"title": "Something else entirely", "addresses": "hazard_exposure"},  # target match
        {"title": "Genuinely new", "addresses": "water_body_proximity"},
    ]}}
    assert _flag_duplicates(proposals, existing) == 2
    ideas = proposals["environment"]["ideas"]
    assert ideas[0]["duplicate_of"]["reason"] == "same title as logged work"
    assert ideas[1]["duplicate_of"]["reason"] == "addresses a shortfall already covered"
    assert "duplicate_of" not in ideas[2]


def test_ideation_survives_an_unreachable_ledger(frame, monkeypatch):
    """Needs are measured data; a ledger outage must not suppress them."""
    from src.decision import needs as needs_module

    def boom(_):
        raise RuntimeError("ledger down")

    monkeypatch.setattr(needs_module, "coverage", boom, raising=False)
    monkeypatch.setattr("src.decision.implementations.coverage", boom)
    out = needs_module.assess([HIGH_SLIDE], frame)
    assert out["ranked"], "needs must still be reported"
    assert out["coverage_error"] and "ledger down" in out["coverage_error"]


# --- agent output is untrusted in shape, not just in content ----------------
# A live ideation run returned `addresses` as a list where the schema asked for
# a string. That turned dict.get(list) into "TypeError: unhashable type: 'list'"
# and lost five minutes of agent work to a 500. These pin the coercion.

def test_targets_accepts_whatever_an_agent_returns():
    from src.decision.ideate import _targets

    assert _targets("flood_risk") == ["flood_risk"]
    assert _targets(["a", "b"]) == ["a", "b"]
    assert _targets(None) == []
    assert _targets("") == []
    assert _targets([" x ", "", None]) == ["x"]
    assert _targets(42) == ["42"]
    assert _targets({"weird": 1})          # a dict stringifies rather than raising


def test_duplicate_check_never_raises_on_malformed_output():
    """A malformed idea skips that idea; it must not fail the request."""
    from src.decision.ideate import _flag_duplicates

    existing = [{"id": 1, "title": "Slope works", "status": "in_progress",
                 "addresses": "hazard_exposure"},
                {"id": 2, "title": "Drainage", "status": "planned",
                 "addresses": ["flood_risk", "climate_vulnerability"]}]
    proposals = {"environment": {"available": True, "ideas": [
        {"title": "Slope Works", "addresses": "unrelated"},              # title match
        {"title": "New", "addresses": ["climate_vulnerability"]},        # list target
        {"title": "Other", "addresses": "hazard_exposure"},              # string target
        {"title": "Clean", "addresses": "water_body_proximity"},         # genuinely new
        "not a dict",                                                    # junk
        {"title": "Odd", "addresses": {"unhashable": 1}},                # dict target
        {},                                                              # empty
    ]}}
    assert _flag_duplicates(proposals, existing) == 3
    ideas = [i for i in proposals["environment"]["ideas"] if isinstance(i, dict)]
    assert "duplicate_of" not in ideas[3]
    assert not any(i.get("duplicate_check_error") for i in ideas)


def test_create_coerces_every_agent_supplied_field():
    """The Implement button must work on the ideas most worth logging."""
    created = impl.create(
        {"title": ["Odd", "Title"], "domain": ["environment"],
         "addresses": ["flood_risk", "climate_vulnerability"],
         "est_cost_inr_crore": "12.5", "feasibility": None,
         "conditions": ["an assessment"], "what": 42},
        [" G10095 ", "G10095", ""], origin="test")
    try:
        assert created["title"] == "Odd, Title"
        assert created["domain"] == "environment"
        assert created["addresses"] == "flood_risk, climate_vulnerability"
        assert created["est_cost_inr_crore"] == 12.5
        assert created["admin_ids"] == ["G10095"]      # trimmed and de-duplicated
        assert created["detail"] == "42"
        assert created["feasibility"] is None
    finally:
        _delete(created["id"])


def test_an_uncostable_idea_is_logged_with_a_null_cost():
    """Agents are told to return null rather than invent a figure; honour it."""
    created = impl.create({"title": "Cannot cost this yet", "domain": "economic",
                           "est_cost_inr_crore": None}, [INLAND], origin="test")
    try:
        assert created["est_cost_inr_crore"] is None
        listed = impl.listing(admin_ids=[INLAND])
        assert any(r["id"] == created["id"] for r in listed["implementations"])
    finally:
        _delete(created["id"])
